In [2]:
import torch

# Everything in pytorch is based on Tensor operations.
# A tensor can have different dimensions
# so it can be 1d, 2d, or even 3d and higher

# scalar, vector, matrix, tensor

# torch.empty(size): uninitiallized

In [3]:
x = torch.empty(1) # scalar
print(x)

tensor([1.8361e+25])


In [4]:
x = torch.empty(2,3) # matrix, 2D
print(x)

tensor([[ 0.0000e+00, -4.6566e-10,  0.0000e+00],
        [-4.6566e-10,  8.4078e-45,  1.1210e-44]])


In [5]:
x = torch.empty(2,2,3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [6]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.8755, 0.1530, 0.0482],
        [0.2508, 0.8821, 0.9624],
        [0.6003, 0.3214, 0.6421],
        [0.6888, 0.0769, 0.0725],
        [0.4077, 0.8682, 0.2635]])


In [7]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [8]:
# check size
print(x.size())

torch.Size([5, 3])


In [9]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


In [10]:
# check type
print(x.dtype)

torch.float16


In [11]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])
